### ISSUE TITLE
History renamed compared to tf1 wrapper

### ISSUE THREAD

**Issue by icfly2** [adriangb/scikeras#227]
I'm mostly through migration to this great project, as part of the move to upgrade to tf2 and noticed that `history` is called `history_` in scikeras. This is documented in the Model documentation but it might be nice to have a note in the migration guide.

As there are some PRs related to this history object I won't make a suggestion for the doc as I don't know how the behaviour changes (for my case it is just a case of renaming).

**Comment by stsievert** [comment]
Renaming `est.history` to `est.history_` would violate [Scikit-learn API's rules on attributes][1].

That said, TF compatibility is a concern. If a `history` attribute is public, it needs to issue a deprecation warning every time it's accessed or set (and should motivate use of `history_`).

Another option is to issue an exception with a helpful error message (basically "use `history_` instead of `history`"). I'm ambivalent on warning vs exception. I think I slightly prefer a warning.

[1]:https://scikit-learn.org/stable/glossary.html#term-attribute

**Comment by adriangb** [comment]
Hi @icfly2  thank you for the issue.

I think the old wrappers [_returned_ a history object](https://github.com/tensorflow/tensorflow/blob/5620b95cbad549c8eb247ce67ed79398c37e639a/tensorflow/python/keras/wrappers/scikit_learn.py#L143-L145) from calling `fit` instead of saving it is `.history` _or_ `.history_`.  So I don't think we renamed the parameter, instead we changed the signature of `fit` and saved the history as an attribute instead. Please let me know if I am missing anything here 😄 

But I do think we should added this to our transition guide. I don't think it made it on there because it was a change done so early in the development of SciKeras (when it was a PR in TensorFlow) that we didn't even have a transition guide 😅 .

**Comment by icfly2** [comment]
Old behaviour in scikit learn and tf1 + keras: `history`
New behaviour in scikeras `history_`

This is completly fine and I think the nameing makes sense with the trailing `_`. Unfortunatly i don't know which version where changed what as I'm changing from scikit learn + tf1 + keras to scikitlearn + tf2 + scikeras. 

I don't think scikeras should change anything, but perhaps a note in the otherwise excellent migration guide would be all that is needed. This is the only undocumented issue i came across when migrating.

**Comment by adriangb** [comment]
@icfly2 , can you check the docs [here](https://www.adriangb.com/scikeras/refs/pull/228/merge/migration.html#fit-returns-self) and see if it answers the question? Thanks!

**Comment by stsievert** [comment]
@icfly2 from the [Keras.fit docs][1], it appears this code works:

``` python
import keras
hist = keras.fit(...)
hist.history
```

However, SciKeras is slightly different:

``` python
from scikeras.wrappers import KerasClassifier
est = KerasClassifier(...)
est.fit(...)
# est = est.fit(...)  # or this line
est.history_
```

Is that what this issue is about?

[1]:https://keras.io/api/models/model_training_apis/#fit-method
