### ISSUE TITLE
Make partial_fit force a single iteration

### ISSUE THREAD

**Issue by adriangb** [adriangb/scikeras#95]
Currently `partial_fit` and `fit` + `warm_start` have the same behavior. I think it would be more useful if we followed [SGD's example](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html#sklearn.linear_model.SGDClassifier.partial_fit) and trained for exactly one epoch when `partial_fit` is called, regardless of the value of `epochs`/`n_iter` passed to `__init__`.

**Comment by gioxc88** [comment]
I wanted to open an issue about it in relation to `dask-ml HyperbandSearchCV`.

I was studying the algorithm more in detail as well as the `dask` implementation of Hyperband. 
My understanding is that when you specify the parameter `max_iter` in `HyperbandSearchCV` this corresponds to the maximum number of calls to `partial_fit`.

In theory one call to `partial_fit` should correspond to one epoch that is one pass through the whole dataset.

In the current implementation it seems that a call to `partial fit` still trains the model for all the epochs but instead of rebuilding the model it uses the same one that was previously fitted, having the effect of updating the current weights.

The workaround to making it work correctly with `HyperbandSearchCV` would be not to specify the epochs in the initialization so that `epochs=1`.

I also believe it would make sense to change the behavior as you mentioned.
 
I would also ask @TomAugspurger's opinion about my understanding of the issue.

Many thanks
Gio

**Comment by TomAugspurger** [comment]
@stsievert is probably better able to answer that.

**Comment by stsievert** [comment]
> The workaround to making [SciKeras] work correctly with HyperbandSearchCV would be not to specify the epochs in the initialization so that epochs=1.

Yes. That's correct. SciKeras should use `epochs=1` to fit inside of [HyperbandSearchCV's rule of thumb][1]. I would probably specify this manually because I don't like relying on defaults.

Of course, `epochs=2` will not throw any errors, but it will require a small modification of the rule of thumb.

Does that answer your question?

> In the current implementation ...

I think you're largely correct. Here's what happens right now:

* HyperbandSearchCV's treats one iteration in `max_iter` as one `partial_fit` call.*
* In most Scikit-learn models, one `partial_fit` call corresponds to one pass through the dataset (e.g, [MLPRegressor], [SGDRegressor]).
* In the current implementation of SciKeras, `partial_fit` and `fit` perform the same action and train for all epochs, not a single pass through the dataset.

<sup>*As detailed in [Hyperband's rule of thumb][1], the number of examples for each call should vary</sup>

[MLPRegressor]:https://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPRegressor.html#sklearn.neural_network.MLPRegressor.partial_fit
[SGDRegressor]:https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor#sklearn.linear_model.SGDRegressor.partial_fit
[1]:https://ml.dask.org/hyper-parameter-search.html#hyperband-parameters-rule-of-thumb

**Comment by adriangb** [comment]
> * In most Scikit-learn models, one `partial_fit` call corresponds to one pass through the dataset
learn.org/stable/modules/generated/sklearn.linear_model.SGDRegressor#sklearn.linear_model.SGDRegressor.partial_fit))

> * In the current implementation of SciKeras, `partial_fit` and `fit` perform the same action and train for all epochs

I think we should make these match. It should be as easy as having `partial_fit` inject `epochs=1` into the `Model.fit` call, right?

**Comment by stsievert** [comment]
Yup. I'm working on a PR for that right now, and it's pretty easy.

**Comment by gioxc88** [comment]
Thank you everyone for confirming, this change would rule out any possible doubt.

**Comment by adriangb** [comment]
> Yup. I'm working on a PR for that right now, and it's pretty easy.

Oh I just started too! I'll let you handle this one, I trust you'll come up with a better solution.
